Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.boot_timeout = 600
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

  config.vm.define "matesantS" do |server|
    server.vm.hostname = "matesantS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder ".", "/vagrant", disabled: false
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end
end
