Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.boot_timeout = 600
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

  config.vm.define "phenriq2S" do |server|
    server.vm.hostname = "matiasS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "csilva-sSW" do |worker|
    worker.vm.hostname = "matiasSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
